### ISSUE TITLE
Z-axis movement is unreliable [was "Recode the Jeenode sending to use ACK"]

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/Tosca#24] opened 2016-02-27 19:11 UTC
The z-axis is sometimes slow to respond and sometimes (@amcewen thinks) misses a whole raise or lower sequence (seen with @goatchurchprime's checkerboard test gcode).

We need to find a way to fix that.

Below is the original suggestion of something to try, but check below for other suggestions...

Continuation of issue 18:  https://github.com/DoESLiverpool/Tosca/issues/18

Current code in https://github.com/DoESLiverpool/Tosca/blob/master/jeenodezdecoder/jeenodezdecoder.ino uses:

```
    rf12_sendStart(1, payload, payloadCount*sizeof(int));
    rf12_sendWait(RF12_NORMAL_SENDWAIT); // wait for send completion
```

Some packets get missed which means the pen doesn't move in time (and gets set at the next heartbeat).  

A solution would be to require ACKs to make sure the packets are getting through (and so it can retry multiple times if it doesn't).  This will improve the relability.  
    http://jeelabs.org/2011/01/12/relaying-rf12-packets/

**Comment by amcewen** [comment] 2016-03-03 11:05
I've marked issue #31 as a duplicate of this, and edited this one to show the problem that needs solving, rather than one of the possible solutions (now that we'd ended up with two issues trying to solve the same thing).

**Comment by amcewen** [comment] 2016-03-03 11:09
Personally I don't think that switching to IR over RF would be a good idea.  With RF we at least have _some_ experience, whereas IR is switching to a whole new domain for all of us.  And when did anyone last have a phone with an IR port?  Or use the one that it had?  I think there's a reason that Bluetooth/Wifi/etc. won out over IrDA :-D

I've got a pair of XBee modules which might be more reliable than the RFM12 modules.  They're on @goatchurchprime's desk at present.  They're targetted at higher bandwidth than the RFM12 modules, if nothing else...

**Comment by amcewen** [comment] 2016-03-15 17:38
Moving to XBee seems to have improved matters considerably.

**Closed as completed by amcewen** 2016-03-15 17:38 UTC
Labels: software, Tosca, Knut
